# Generated by Django 5.1.1 on 2024-11-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('producto_solicitud', models.CharField(max_length=100)),
                ('cantidad_solicitud', models.PositiveIntegerField()),
                ('descripcion_cotizacion', models.TextField()),
                ('estado_solicitud', models.CharField(default='En espera', max_length=50)),
                ('estadoActividad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_De_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_aprobada', models.PositiveIntegerField(default=1)),
                ('tiempo_entrega', models.DateTimeField()),
                ('condiciones', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estado', models.CharField(default='Por revisar', max_length=50)),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_compra', to='API.solicitudcotizacion')),
            ],
        ),
    ]
